export const tags = [
  "Spa in Anandnagar",
  "Spa in Ambli",
  "Spa in Ashram Road",
  "Spa in Drive in Road",
  "Spa in Gota",
  "Spa in Jagatpur",
  "Spa in Memnagar",
  "Spa in Naranpura",
  "Spa in Prahladnagar",
  "Spa in Satellite",
  "Spa in Jagatpur",
  "Spa in Shilaj",
  "Spa in Gota",
  "Spa in Sola",
  "Spa in Ashram Road",
  "Spa in Thaltej",
  "Spa in Vastrapur",
  "Spa in Ambli",
  "Spa in Ashram Road",
  "Spa in Drive in Road",
  "Spa in Gota",
  "Spa in Jagatpur",
  "Spa in Memnagar",
  "Spa in Naranpura",
  "Spa in Prahladnagar",
  "Spa in Satellite",
  "Spa in Jagatpur",
];

export const spaNearYou = [
  {
    name: "Aroma The Luxurious Spa",
    img: "spa.png",
    location: "Kudasan, Gandhinagar",
    phone: Number("09667050051"),
    therapy: "Couple Therapy",
    callLink: "/tag",
  },
  {
    name: "Aroma The Luxurious Spa",
    img: "spa.png",
    location: "Kudasan, Gandhinagar",
    phone: Number("09667050051"),
    therapy: "Couple Therapy",
    callLink: "/tag",
  },
  {
    name: "Aroma The Luxurious Spa",
    img: "spa.png",
    location: "Kudasan, Gandhinagar",
    phone: Number("09667050051"),
    therapy: "Couple Therapy",
    callLink: "/tag",
  },
  {
    name: "Aroma The Luxurious Spa",
    img: "spa.png",
    location: "Kudasan, Gandhinagar",
    phone: Number("09667050051"),
    therapy: "Couple Therapy",
    callLink: "/tag",
  },
  {
    name: "Aroma The Luxurious Spa",
    img: "spa.png",
    location: "Kudasan, Gandhinagar",
    phone: Number("09667050051"),
    therapy: "Couple Therapy",
    callLink: "/tag",
  },
  {
    name: "Aroma The Luxurious Spa",
    img: "spa.png",
    location: "Kudasan, Gandhinagar",
    phone: Number("09667050051"),
    therapy: "Couple Therapy",
    callLink: "/tag",
  },
  {
    name: "Aroma The Luxurious Spa",
    img: "spa.png",
    location: "Kudasan, Gandhinagar",
    phone: Number("09667050051"),
    therapy: "Couple Therapy",
    callLink: "/tag",
  },
  {
    name: "Aroma The Luxurious Spa",
    img: "spa.png",
    location: "Kudasan, Gandhinagar",
    phone: Number("09667050051"),
    therapy: "Couple Therapy",
    callLink: "/tag",
  },
];

export const LuxuriousSpa = [
  {
    name: "Luxurious Spa",
    img: "spa.png",
    location: "Kudasan, Gandhinagar",
    phone: Number("09667050051"),
    therapy: "Couple Therapy",
    callLink: "/tag",
  },
  {
    name: "Luxurious Spa",
    img: "spa.png",
    location: "Kudasan, Gandhinagar",
    phone: Number("09667050051"),
    therapy: "Couple Therapy",
    callLink: "/tag",
  },

  {
    name: "Luxurious Spa",
    img: "spa.png",
    location: "Kudasan, Gandhinagar",
    phone: Number("09667050051"),
    therapy: "Couple Therapy",
    callLink: "/tag",
  },
  {
    name: "Luxurious Spa",
    img: "spa.png",
    location: "Kudasan, Gandhinagar",
    phone: Number("09667050051"),
    therapy: "Couple Therapy",
    callLink: "/tag",
  },
  {
    name: "Luxurious Spa",
    img: "spa.png",
    location: "Kudasan, Gandhinagar",
    phone: Number("09667050051"),
    therapy: "Couple Therapy",
    callLink: "/tag",
  },
  {
    name: "Luxurious Spa",
    img: "spa.png",
    location: "Kudasan, Gandhinagar",
    phone: Number("09667050051"),
    therapy: "Couple Therapy",
    callLink: "/tag",
  },
  {
    name: "Luxurious Spa",
    img: "spa.png",
    location: "Kudasan, Gandhinagar",
    phone: Number("09667050051"),
    therapy: "Couple Therapy",
    callLink: "/tag",
  },
];

export const topRatedSpa = [
  {
    name: "Top Rated Spa",
    img: "spa.png",
    location: "Kudasan, Gandhinagar",
    phone: Number("09667050051"),
    therapy: "Couple Therapy",
    callLink: "/tag",
  },
  {
    name: "Top Rated Spa",
    img: "spa.png",
    location: "Kudasan, Gandhinagar",
    phone: Number("09667050051"),
    therapy: "Couple Therapy",
    callLink: "/tag",
  },
  {
    name: "Top Rated Spa",
    img: "spa.png",
    location: "Kudasan, Gandhinagar",
    phone: Number("09667050051"),
    therapy: "Couple Therapy",
    callLink: "/tag",
  },
  {
    name: "Top Rated Spa",
    img: "spa.png",
    location: "Kudasan, Gandhinagar",
    phone: Number("09667050051"),
    therapy: "Couple Therapy",
    callLink: "/tag",
  },
  {
    name: "Top Rated Spa",
    img: "spa.png",
    location: "Kudasan, Gandhinagar",
    phone: Number("09667050051"),
    therapy: "Couple Therapy",
    callLink: "/tag",
  },
  {
    name: "Top Rated Spa",
    img: "spa.png",
    location: "Kudasan, Gandhinagar",
    phone: Number("09667050051"),
    therapy: "Couple Therapy",
    callLink: "/tag",
  },
  {
    name: "Top Rated Spa",
    img: "spa.png",
    location: "Kudasan, Gandhinagar",
    phone: Number("09667050051"),
    therapy: "Couple Therapy",
    callLink: "/tag",
  },
];

export const offers = [
  "deal.png",
  "deal.png",
  "deal.png",
  "deal.png",
  "deal.png",
  "deal.png",
];

export const specialIcons = [
  "1.png",
  "2.png",
  "3.png",
  "4.png",
  "5.png",
  "6.png",
  "7.png",
];

export const therapy = [
  {
    name: "Swedish Therapy",
    img: "therapy.png",
  },
  {
    name: "Oil Massage Therapy",
    img: "therapy.png",
  },
  {
    name: "Cream Therapy",
    img: "therapy.png",
  },
  {
    name: "Swedish Therapy",
    img: "therapy.png",
  },
  {
    name: "Oil Massage Therapy",
    img: "therapy.png",
  },
  {
    name: "Cream Therapy",
    img: "therapy.png",
  },
  {
    name: "Swedish Therapy",
    img: "therapy.png",
  },
];
export const topDestinations = [
  "img1.png",
  "img2.png",
  "img3.png",
  "img4.png",
  "img5.png",
  "img6.png",
];
export const topDestinationsLocations = [
  "London",
  "Bangkok",
  "England",
  "Singapore",
  "Italy",
];
